# https://dependabot.com/docs/config-file

version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "any"
          update_type: "all"
    commit_message:
      prefix: "dependencies"
