name: Check license approvals

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: License Approval
      uses: ralexander-phi/license_approval@0.0.1
