name: Check node licenses

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: License Checker
      uses: docker://cdssnc/node-license-checker-github-action
      with:
        args: --onlyAllow 'MIT; MIT OR X11; BSD; ISC'
