name: Check node licenses

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: License Checker
      uses: kt3k/license_checker@v1.0.1
      with:
        args: "--onlyAllow 'MIT; MIT OR X11; BSD; ISC'"
