name: Main
on: push
jobs:
  test-with-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
      - name: Test with puppeteer
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn test
