name: Check for secrets in the source code

on: [push]

jobs:
  secrets-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: eshork/gitleaks-action@v1.0.0
